exports.seed = function(knex) {
  return knex('players').del()
    .then(function () {
      return knex('players').insert([
        { first_name: 'Raheem', last_name: 'Sterling', age: 27, nationality: 'English', position: 'Forward', club_id: 1 },
        { first_name: 'Lamine', last_name: 'Yamal', age: 16, nationality: 'Spanish', position: 'Forward', club_id: 2 },
        { first_name: 'Karim', last_name: 'Benzema', age: 34, nationality: 'French', position: 'Forward', club_id: 3 },
        { first_name: 'Mason', last_name: 'Mount', age: 23, nationality: 'English', position: 'Midfielder', club_id: 4 },
        { first_name: 'Mohamed', last_name: 'Salah', age: 30, nationality: 'Egyptian', position: 'Forward', club_id: 5 },
        { first_name: 'Lionel', last_name: 'Messi', age: 36, nationality: 'Argentinian', position: 'Forward', club_id: 6 },
        { first_name: 'Robert', last_name: 'Lewandowski', age: 34, nationality: 'Polish', position: 'Forward', club_id: 7 },
        { first_name: 'Cristiano', last_name: 'Ronaldo', age: 37, nationality: 'Portuguese', position: 'Forward', club_id: 8 },
        { first_name: 'Zlatan', last_name: 'Ibrahimovic', age: 40, nationality: 'Swedish', position: 'Forward', club_id: 9 },
        { first_name: 'Romelu', last_name: 'Lukaku', age: 29, nationality: 'Belgian', position: 'Forward', club_id: 10 },
        { first_name: 'Kylian', last_name: 'Mbappe', age: 22, nationality: 'French', position: 'Forward', club_id: 6 },
        { first_name: 'Sergio', last_name: 'Ramos', age: 35, nationality: 'Spanish', position: 'Defender', club_id: 6 },
        { first_name: 'Luka', last_name: 'Modric', age: 36, nationality: 'Croatian', position: 'Midfielder', club_id: 3 },
        { first_name: 'Eden', last_name: 'Hazard', age: 30, nationality: 'Belgian', position: 'Forward', club_id: 3 },
        { first_name: 'Neymar', last_name: 'Jr', age: 29, nationality: 'Brazilian', position: 'Forward', club_id: 6 },
        { first_name: 'Virgil', last_name: 'van Dijk', age: 30, nationality: 'Dutch', position: 'Defender', club_id: 5 },
        { first_name: 'Alisson', last_name: 'Becker', age: 28, nationality: 'Brazilian', position: 'Goalkeeper', club_id: 5 },
        { first_name: 'Kevin', last_name: 'De Bruyne', age: 30, nationality: 'Belgian', position: 'Midfielder', club_id: 1 },
        { first_name: 'Phil', last_name: 'Foden', age: 21, nationality: 'English', position: 'Midfielder', club_id: 1 },
        { first_name: 'Bruno', last_name: 'Fernandes', age: 27, nationality: 'Portuguese', position: 'Midfielder', club_id: 8 },
        { first_name: 'Jadon', last_name: 'Sancho', age: 21, nationality: 'English', position: 'Forward', club_id: 8 },
        { first_name: 'Joshua', last_name: 'Kimmich', age: 26, nationality: 'German', position: 'Midfielder', club_id: 7 },
        { first_name: 'Manuel', last_name: 'Neuer', age: 35, nationality: 'German', position: 'Goalkeeper', club_id: 7 },
        { first_name: 'Paulo', last_name: 'Dybala', age: 27, nationality: 'Argentinian', position: 'Forward', club_id: 8 },
        { first_name: 'Lautaro', last_name: 'Martinez', age: 24, nationality: 'Argentinian', position: 'Forward', club_id: 10 },
        { first_name: 'Leonardo', last_name: 'Bonucci', age: 34, nationality: 'Italian', position: 'Defender', club_id: 8 },
        { first_name: 'Gianluigi', last_name: 'Donnarumma', age: 22, nationality: 'Italian', position: 'Goalkeeper', club_id: 9 },
        { first_name: 'Theo', last_name: 'Hernandez', age: 24, nationality: 'French', position: 'Defender', club_id: 9 },
        { first_name: 'Fikayo', last_name: 'Tomori', age: 23, nationality: 'English', position: 'Defender', club_id: 9 },
        { first_name: 'Hakan', last_name: 'Calhanoglu', age: 27, nationality: 'Turkish', position: 'Midfielder', club_id: 10 },
        { first_name: 'Marcelo', last_name: 'Brozovic', age: 29, nationality: 'Croatian', position: 'Midfielder', club_id: 10 },
        { first_name: 'Antonio', last_name: 'Rudiger', age: 28, nationality: 'German', position: 'Defender', club_id: 4 },
        { first_name: 'N\'Golo', last_name: 'Kante', age: 30, nationality: 'French', position: 'Midfielder', club_id: 4 },
        { first_name: 'Timo', last_name: 'Werner', age: 25, nationality: 'German', position: 'Forward', club_id: 4 },
        { first_name: 'Kai', last_name: 'Havertz', age: 22, nationality: 'German', position: 'Midfielder', club_id: 4 },
        { first_name: 'Hakim', last_name: 'Ziyech', age: 28, nationality: 'Moroccan', position: 'Midfielder', club_id: 4 },
        { first_name: 'Christian', last_name: 'Pulisic', age: 23, nationality: 'American', position: 'Midfielder', club_id: 4 },
        { first_name: 'Reece', last_name: 'James', age: 21, nationality: 'English', position: 'Defender', club_id: 4 },
        { first_name: 'Ben', last_name: 'Chilwell', age: 24, nationality: 'English', position: 'Defender', club_id: 4 },
        { first_name: 'Thiago', last_name: 'Silva', age: 36, nationality: 'Brazilian', position: 'Defender', club_id: 4 },
        { first_name: 'Edouard', last_name: 'Mendy', age: 29, nationality: 'Senegalese', position: 'Goalkeeper', club_id: 4 },
        { first_name: 'Mateo', last_name: 'Kovacic', age: 27, nationality: 'Croatian', position: 'Midfielder', club_id: 4 },
        { first_name: 'Cesar', last_name: 'Azpilicueta', age: 32, nationality: 'Spanish', position: 'Defender', club_id: 4 },
        { first_name: 'Olivier', last_name: 'Giroud', age: 35, nationality: 'French', position: 'Forward', club_id: 9 },
      ]);
    });
};
